---
- name: import zabbix yum
  shell: rpm -Uvh https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm
  ignore_errors: true

- name: dnf clean all
  shell: dnf clean all

- name: install zabbix-agent
  yum:
    name: zabbix-agent
    state: latest

- name: Enable zabbix-agent, and not touch the state
  service:
    name: zabbix-agent
    enabled: yes

- name: sync zabbix-agent configure file
  copy:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Start service zabbix-agent, if not started
  service:
    name: zabbix-agent
    state: started
