filebeat.inputs:
- type: log 
  enabled: true
  paths:
    - /yl/logs/deploy/java/*/*.log
  fields_under_root: true
  # 日志为json格式开启
  # json.keys_under_root: true
  # json.overwrite_keys: true
  fields:
    type: backend
    env: test
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after

filebeat.config.modules:
   path: ${path.config}/modules.d/*.yml
   reload.enabled: false

setup.template.settings:
  index.number_of_shards: 5

# output.kafka:
#   hosts: ["10.4.18.51:9092","10.4.18.52:9092","10.4.18.53:9092"]
#   topic: 'app_backend'
#   partition.round_robin:
#     reachable_only: false
#   required_acks: 1
#   compression: gzip
#   max_message_bytes: 10000000

output.logstash:
  hosts: ["172.16.82.4:5044"]