---
- name: Rollback project to default version
  hosts: "{{ app_host }}"
  gather_facts: no
  vars:
    ansistrano_deploy_to: "/opt/app/{{ app_name }}"
    ansistrano_remove_rolled_back: yes
  roles:
    - { role: rollback }
